const GET_PRODUCTS = 'GET_PRODUCTS';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

export {
    GET_PRODUCTS,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    CHECKOUT_SUCCESS,
    CHECKOUT_FAILURE
}